language: php

php:
  - 7.2

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed

before_install:
  - phpenv config-rm xdebug.ini || return

script:
  - vendor/bin/phpunit

notifications:
  email: false

after_success:
  - wget https://raw.githubusercontent.com/Woeler/discord-travis/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/Woeler/discord-travis/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL